# Generated by Django 4.0.2 on 2022-02-15 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_location_alter_profile_short_intro_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='social_instagram',
            new_name='social_twitter',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='social_youtube',
        ),
    ]
